### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by hvds** [graphql-perl/graphql-perl#7]
As discussed at LPW, it would be useful to include some sort of roadmap document showing what's still to do and roughly what order you plan to do it.

Hugo

**Comment by mohawk2** [comment]
Thanks for this!

Things still to do, roughly in order:

* [ ] Finish Dockerising `GraphQL` and its Mojolicious plugins and converters, currently on branches; also make the "sample" OpenAPI applet use an environment variable if given, for where to get its schema
* [x] Finish the `async` branch on `graphql-perl`
* [x] Integrate that with the Mojolicious plugin for proper asynchronous operation

These next, order uncertain:

* [ ] Make a Federate plugin that can introspect other GraphQL services, and merge them into one schema
* [ ] Make a Transform plugin that can introspect another GraphQL service, and apply a transformation
* [ ] Convert the DBIC plugin to use a Relay-ish schema OR put a layer in front using the Transform from above
* [ ] Sample app, almost certainly a simple blog, that uses a DBIC schema and makes it work with React/Relay
* [ ] Update `DBIx::Class::Schema::Loader` so that as well as talking directly to a `DBI`, it can also introspect an `SQL::Translator::Schema`
* [ ] Make a working `from_graphql` for the DBIC converter, so you could make a GraphQL schema and it will generate a database for you
* [ ] For a given set of top-level tables, generate audit tables and triggers so that on any mutation, the previous state will be recorded, journal-style

What are your thoughts?

**Comment by mohawk2** [comment]
* [ ] Another thing: a `graphql` command for Mojolicious, that can make queries and/or introspect GraphQL services.
